(define (hanoi n xx yy zz)
  (if (> n 0)
      (let ((nn (hanoi (- n 1) xx zz yy)))
	(display xx)
	(display " -> ")
	(display zz)
	(newline)
	(+ 1 nn (hanoi (- n 1) yy xx zz)))
      0))

(hanoi 4 "x" "y" "z")
(hanoi 3 "x" "y" "z")
(hanoi 2 "x" "y" "z")
(hanoi 1 "x" "y" "z")
